SELECT MAX(SAL), MIN(SAL), TRUNC(AVG(SAL)), SUM(SAL)
FROM SCOTT.EMP;

SELECT MIN(HIREDATE), MAX(HIREDATE), MIN(ENAME), MAX(ENAME)
FROM SCOTT.EMP;

SELECT COUNT(*), COUNT(COMM)
FROM SCOTT.EMP;

SELECT AVG(COMM), AVG(NVL(COMM,0))
FROM SCOTT.EMP;

SELECT DEPTNO, SUM(SAL)
FROM SCOTT.EMP
GROUP BY DEPTNO
ORDER BY DEPTNO;

SELECT DEPTNO, JOB, SUM(SAL)
FROM SCOTT.EMP
GROUP BY DEPTNO, JOB
ORDER BY DEPTNO, JOB;