SELECT ENAME, SAL, SAL+500
FROM SCOTT.EMP;

SELECT ENAME, SAL, SAL*12+100
FROM SCOTT.EMP;

SELECT ENAME, SAL, 12*(SAL+100)
FROM SCOTT.EMP;

SELECT ENAME FUNCIONARIO, SAL "SALARIO DO COLABORADOR", 12*(SAL+100) AS "SALARIO ANUAL COM BONUS"
FROM SCOTT.EMP;

SELECT ENAME, JOB, SAL, ENAME || ' TEM O CARGO DE ' || JOB || ' E GANHA ' || SAL AS "FUNCIONARIOS - CARGOS E SALARIOS"
FROM SCOTT.EMP;

SELECT DISTINCT JOB 
FROM SCOTT.EMP;