SELECT ENAME, UPPER(ENAME), LOWER(ENAME), INITCAP(ENAME)
FROM SCOTT.EMP;

SELECT ENAME, JOB, CONCAT(ENAME,JOB), SUBSTR(ENAME,1,3), INSTR(ENAME,'A'), LENGTH(ENAME)
FROM SCOTT.EMP;

SELECT ROUND(42.929), TRUNC(42.929)
FROM SCOTT.EMP;

SELECT ROUND(42.929,2), TRUNC(42.929,2)
FROM SCOTT.EMP;

SELECT ENAME, SAL, MOD(SAL,2)
FROM SCOTT.EMP;