SELECT SYSDATE FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DD/MONTH/YYYY') FROM DUAL;

SELECT TO_CHAR(SYSDATE, 'DAY/YEAR') FROM DUAL;

SELECT ENAME, HIREDATE, TRUNC(SYSDATE - HIREDATE) AS DIAS, TRUNC((SYSDATE - HIREDATE)/7) AS SEMANAS,
TRUNC((SYSDATE - HIREDATE)/365) AS ANOS, TRUNC((SYSDATE - HIREDATE)*24) AS HORAS
FROM SCOTT.EMP;

SELECT ENAME, SAL,TO_CHAR(SAL, 'L999,999,999.99')
FROM SCOTT.EMP;