SELECT ENAME, SAL, COMM, SAL*12+COMM
FROM SCOTT.EMP;

SELECT ENAME, SAL, COMM, SAL*12+NVL(COMM,0)
FROM SCOTT.EMP;

SELECT ENAME, SAL, JOB,
DECODE(JOB, 'CLERK', SAL*1.1,
            'MANAGER', SAL*1.15,
            'SALESMAN', SAL*1.2,
        SAL) AS "SALARIO REVISADO"
FROM SCOTT.EMP;