SELECT EMP.ENAME, EMP.SAL, DEPT.DNAME, DEPT.DEPTNO, DEPT.LOC
FROM SCOTT.EMP EMP JOIN SCOTT.DEPT DEPT
ON (EMP.DEPTNO = DEPT.DEPTNO);

SELECT E.LAST_NAME, D.DEPARTMENT_NAME, L.CITY
FROM HR.EMPLOYEES E JOIN HR.DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
JOIN HR.LOCATIONS L
ON (D.LOCATION_ID = L.LOCATION_ID);