 SELECT E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM HR.EMPLOYEES E LEFT OUTER JOIN HR.DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID)
ORDER BY E.LAST_NAME;

SELECT E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM HR.EMPLOYEES E RIGHT OUTER JOIN HR.DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID);

SELECT E.LAST_NAME, D.DEPARTMENT_ID, D.DEPARTMENT_NAME
FROM HR.EMPLOYEES E FULL OUTER JOIN HR.DEPARTMENTS D
ON (E.DEPARTMENT_ID = D.DEPARTMENT_ID);