Algoritmo "Uso Repita...Até"
// Disciplina   : [Linguagem e Lógica de Programação]
// Professor   : Antonio Carlos Nicolodi 
// Descrição   : Aqui você descreve o que o programa faz! (função)
// Autor(a)    : Nome do(a) aluno(a)
// Data atual  : 10/02/2026
Var
// Seção de Declarações das variáveis 
   k: inteiro

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
   k <- 1
   repita
         escreval("O valor de K é: ", k)
         k <- k + 1
   ate k > 10

Fimalgoritmo