SELECT * FROM SCOTT.EMP;

CREATE OR REPLACE VIEW DEPT_VU_10
AS SELECT ENAME, SAL, DEPTNO
FROM SCOTT.EMP
WHERE DEPTNO = 10;

SELECT * FROM DEPT_VU_10;

CREATE OR REPLACE VIEW SAL_VU_30
AS SELECT ENAME NOME, SAL SALARIO, DEPTNO COD_DEPTO
FROM SCOTT.EMP
WHERE DEPTNO = 30;

SELECT * FROM SAL_VU_30;