CREATE OR REPLACE VIEW DEPT_VU_30
AS SELECT D.DNAME DEPTO, MIN(E.SAL) MENOR, MAX(E.SAL) MAIOR, AVG(E.SAL)MEDIA
FROM SCOTT.EMP E JOIN SCOTT.DEPT D
ON (E.DEPTNO = D.DEPTNO)
GROUP BY D.DNAME;

SELECT * FROM DEPT_VU_30;

CREATE OR REPLACE VIEW SAL_VU_30
AS SELECT EMPNO, ENAME, SAL, DEPTNO
FROM SCOTT.EMP
WHERE DEPTNO = 30;

SELECT * FROM SAL_VU_30;

DELETE FROM SAL_VU_30;

CREATE OR REPLACE VIEW SAL_VU_30
AS SELECT EMPNO, ENAME, SAL, DEPTNO
FROM SCOTT.EMP
WHERE DEPTNO = 30
WITH READ ONLY;

SELECT * FROM SAL_VU_30;

DELETE FROM SAL_VU_30;