CREATE TABLE COPIA_DEPT AS (SELECT * FROM SCOTT.EMP);

SELECT * FROM COPIA_DEPT;

CREATE SEQUENCE DEPT_DEPTNO
START WITH 50
INCREMENT BY 10
MAXVALUE 90;

INSERT INTO COPIA_DEPT VALUES (DEPT_DEPTNO.nextval, 'COMERCIAL', 'SP');

SELECT * FROM COPIA_DEPT;

INSERT INTO COPIA_DEPT VALUES (DEPT_DEPTNO.nextval, 'FABRICA', 'MG');

SELECT * FROM COPIA_DEPT;

ALTER SEQUENCE DEPT_DEPTNO
INCREMENT BY 1
MAXVALUE 100;

INSERT INTO COPIA_DEPT VALUES (DEPT_DEPTNO.nextval, 'GALPAO', 'MG');

SELECT * FROM COPIA_DEPT;

DROP SEQUENCE DEPT_DEPTNO;

SELECT * FROM COPIA_DEPT;